# Variables
@baseURL=http://localhost:8080

# Endpoints

# Get Games
@name=Get Games
GET {{baseURL}}/games

###

# Get Game by ID
@name=Get Game by ID
GET {{baseURL}}/games/1

###

# Get Game by ID
@name=Get GameList
GET {{baseURL}}/lists

###

# Get Game by List
@name=Get Game by List
GET {{baseURL}}/lists/1/games